// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateUser = `-- name: CreateUser :one
INSERT INTO users 
(
  username, 
  password, 
  first_name, 
  last_name
)
VALUES ($1, $2, $3, $4) 
RETURNING id, username, first_name, last_name, last_login
`

type CreateUserParams struct {
	Username  string `json:"username"`
	Password  string `json:"password"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

type CreateUserRow struct {
	ID        int32            `json:"id"`
	Username  string           `json:"username"`
	FirstName string           `json:"first_name"`
	LastName  string           `json:"last_name"`
	LastLogin pgtype.Timestamp `json:"last_login"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, CreateUser,
		arg.Username,
		arg.Password,
		arg.FirstName,
		arg.LastName,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.LastLogin,
	)
	return i, err
}

const UsernameExists = `-- name: UsernameExists :one
SELECT EXISTS (
    SELECT id, username, password, first_name, last_name, last_login, created_at
    FROM users 
    WHERE username = $1
)
`

func (q *Queries) UsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, UsernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
