// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID        int32            `json:"id"`
	UserID    int32            `json:"user_id"`
	Content   string           `json:"content"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID        int32  `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

type UserLogin struct {
	ID        int32            `json:"id"`
	Token     string           `json:"token"`
	LastLogin pgtype.Timestamp `json:"last_login"`
	Username  string           `json:"username"`
	Password  string           `json:"password"`
}
